### PR TITLE
Fix swift 5.4 issues with allCases

### LINKED ISSUE #136: Invalid redeclaration of synthesized implementation for protocol requirement 'allCases'
Building the package on Xcode 12.5 I am getting such an error on line
`        public static let allCases: Set<MajorServiceClass> = [`
in 
`ClassOfDevice.swift`.

### PR DESCRIPTION
**Pull request by ksinghal**
**Issue**

Fixes #136.

**What does this PR Do?**

Fix swift 5.4 issues with allCases by replacing sets with array, fix associated tests.

see here for more details on this as the preferred solution:
https://forums.swift.org/t/invalid-redeclaration-of-synthesized-implementation-for-protocol-requirement-allcases/47715/3

**Where should the reviewer start?**

All enums affected

**Sweet giphy showing how you feel about this PR**

Giphy

### CODE REVIEW

File: Sources/Bluetooth/L2CAPSocket.swift [hunk 1]
```diff
@@ -9,7 +9,7 @@
 import Foundation
 
 /// L2CAP Socket protocol.
-public protocol L2CAPSocketProtocol: class {
+public protocol L2CAPSocketProtocol: AnyObject {
```
Comment (colemancda) [inline Sources/Bluetooth/L2CAPSocket.swift:12]: This is a separate issue from the `allCases`. I find it hard to believe simply declaring a `class` protocol is broken or has been changed in Swift 5.4. If there has been a breaking language change please link to the Swift Evolution proposal or discussion in Forum.

**Review by colemancda — CHANGES_REQUESTED** [review]
We need to test this code in Swift 5.1, 5.3 and 5.4 on Armv7, Arm64 and x86_64.
Also, please link to Swift Evolution proposal, swift.org blog or Xcode changelog where the language changes have been specified.
